### ISSUE TITLE
Please make a new release :)

### ISSUE THREAD

**Issue by hartwork** [TobiX/screentest#1]
This 6d101436ba0721e86b1e20452719d755d1352666 and this 2a79bac623460a340edb063b997e77eff1336480 would be cool to have in a release, especially.

Thanks and best, Sebastian

**Comment by TobiX** [comment]
Better late then never.

**Comment by hartwork** [comment]
Thank you!

I have [bumped screentest to 2.1](https://gitweb.gentoo.org/proj/betagarden.git/commit/?id=f3f63643329becce80559fc158104870224be865) in Gentoo betagarden just now.
