### ISSUE TITLE
WISH: add plain color screens and gradients

### ISSUE THREAD

**Issue by Code7R** [TobiX/screentest#2]
Hello,

when you are looking for banal dead pixel errors, it would be nice to have basic colored screens, with R/G/B and black and white, of course.

Another useful thing would be gradients between foreground and background colors, maybe also have a configurable direction (corner to corner or horizontal or vertical).

Thanks you.

**Comment by TobiX** [comment]
The first part was just contributed in #5

**Comment by markuspg** [comment]
I made an attempt to implement the _gradient_ part of this issue. @Code7R: If you like you are welcome to try #15 and give feedback if this is what you were looking for.

With a left-click it is possible to cycle through different directions.

**Comment by TobiX** [comment]
I consider this fixed in 3.0
